/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import LogicaNegocio.TransaccionesUsuario;
import com.placeholder.PlaceHolder;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author Alexis Aguilar
 */
public class frmUsuario extends javax.swing.JPanel {

    TransaccionesUsuario ob = new TransaccionesUsuario();
    private TableRowSorter trsfiltro; //creamos el filtro
    String filtro;
    /**
     * Creates new form frmUsuario
     */
    public frmUsuario() {
        initComponents();
        llenar();
        this.setMaximumSize(getMaximumSize());
        holders();
        this.jLabel1.setFocusable(true);
    }
    
    public void holders(){
        PlaceHolder holder;
        holder=new PlaceHolder(txtbuscardato,"Buscar Usuarios");
    } 
    
    public void llenar(){
        this.jTable1.setModel(ob.mostrar());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtbuscardato = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Usuarios del Sistema");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 710, 300));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtbuscardato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscardatoKeyReleased(evt);
            }
        });
        jPanel2.add(txtbuscardato, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 407, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pdf.png"))); // NOI18N
        jButton1.setText("Reporte");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 122, 34));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bu.png"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 34));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("BUSCAR USUARIOS:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 710, 90));
    }// </editor-fold>//GEN-END:initComponents

    public void filtro() {
        //Obtiene el valor del JTextField para el filtro
        String filtro = txtbuscardato.getText();    
        trsfiltro.setRowFilter(RowFilter.regexFilter("(?i)"+txtbuscardato.getText(),0,1,2,3));
}
    
    private void txtbuscardatoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscardatoKeyReleased
        txtbuscardato.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                filtro();
            }
        });
        trsfiltro = new TableRowSorter(ob.mostrar());
        jTable1.setRowSorter(trsfiltro);
    }//GEN-LAST:event_txtbuscardatoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtbuscardato;
    // End of variables declaration//GEN-END:variables
}
